
# How long to wait in between sending each packet.
packet-interval: 5

# Whether players should (false) or shouldn't (true) be shown by default. Set to true in order to require opt-in via the command.
visibility-opt-in: false

# Whether player visibility changes should be saved.
persistent-visibility: false

# Allow players with the "" permission to see all players, regardless of any visibility status.
# By default, all players will have this. The permission node openservermap.overridevis needs to be configured if this is enabled.
# If enabled, this permission is always applied for operators
override-view: false

# Deny players with the "" permission from seeing any players, regardless of any visibility status.
# By default, all players will have this. The permission node openservermap.denyvis needs to be configured if this is enabled.
# If enabled, this permission is never applied for operators
deny-view: false

# Whether to send data on players that are in spectator mode
transmit-spectators: true

