name: OpenServerMap
version: '1.0'
main: net.mmly.openservermap.OpenServerMap
api-version: '1.21'
description: "Server-side integration for OpenMineMap"

author: "MinemasterLegacy"
permissions:
  openservermap.viscommands:
    description: "Permissions to allow players that have it to use visibility commands"
    default: not op
  openservermap.denyvis:
    description: "Permission that denies players that have it from receiving map data. Will only work with the deny-view config option set to true."
    default: not op
  openservermap.overridevis:
    description: "Permission that overrides other players' visibility settings for players who have it. Will only work with the override-view config option set to true."
    default: not op